# Generated by Django 5.2.5 on 2025-09-13 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0002_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('funcionarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_setor', to='pessoa.funcionario')),
            ],
        ),
    ]
