# Generated by Django 5.2.5 on 2025-10-26 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setor',
            name='funcionarios',
        ),
    ]
