# Generated by Django 5.2.5 on 2025-09-13 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0002_funcionario'),
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=150)),
                ('bairro', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=20)),
                ('numero', models.CharField(max_length=10)),
                ('cep', models.CharField(max_length=10)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco_funcionario', to='pessoa.funcionario')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco_secretaria', to='secretaria.secretaria')),
            ],
        ),
    ]
