# Generated by Django 5.2.5 on 2025-09-28 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
        ('pessoa', '0003_administrador_funcionario_secretaria_pessoaprocesso'),
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endereco_funcionario', to='pessoa.funcionario'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endereco_secretaria', to='secretaria.secretaria'),
        ),
    ]
