# Generated by Django 5.2.5 on 2025-08-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data_criacao', models.DateField()),
                ('data_edicao', models.DateField()),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
    ]
