# Generated by Django 5.2.5 on 2025-09-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='data_edicao',
            field=models.DateField(null=True),
        ),
    ]
