# Generated by Django 5.2.5 on 2025-09-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0002_alter_processo_data_edicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='descricao',
            field=models.TextField(),
        ),
    ]
