# Generated by Django 5.2.5 on 2025-10-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0004_alter_processo_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoaprocesso',
            name='codigo',
            field=models.CharField(max_length=6),
        ),
    ]
