# Generated by Django 5.2.5 on 2025-10-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0005_alter_pessoaprocesso_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoaprocesso',
            old_name='data',
            new_name='data_inicio',
        ),
        migrations.AddField(
            model_name='pessoaprocesso',
            name='data_termino',
            field=models.DateField(null=True),
        ),
    ]
