# Generated by Django 5.2.5 on 2025-09-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_administrador_funcionario_secretaria_pessoaprocesso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PessoaProcesso',
        ),
    ]
