# Generated by Django 5.2.5 on 2025-10-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_delete_pessoaprocesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
