# Generated by Django 5.2.5 on 2025-10-26 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0006_alter_pessoa_email'),
        ('secretaria', '0001_initial'),
        ('setor', '0002_remove_setor_funcionarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_setor', to='setor.setor'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_secretaria', to='secretaria.secretaria'),
        ),
    ]
