# Generated by Django 5.2.5 on 2025-10-26 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0007_funcionario_setor_alter_funcionario_secretaria'),
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='secretaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_secretaria', to='secretaria.secretaria'),
        ),
    ]
